// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"mini-paas/ent/deployments"
	"mini-paas/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Deployments is the model entity for the Deployments schema.
type Deployments struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Branch holds the value of the "branch" field.
	Branch string `json:"branch,omitempty"`
	// ImageTag holds the value of the "image_tag" field.
	ImageTag string `json:"image_tag,omitempty"`
	// RepoURL holds the value of the "repo_url" field.
	RepoURL string `json:"repo_url,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DeploymentsQuery when eager-loading is set.
	Edges            DeploymentsEdges `json:"edges"`
	user_deployments *int
	selectValues     sql.SelectValues
}

// DeploymentsEdges holds the relations/edges for other nodes in the graph.
type DeploymentsEdges struct {
	// Author holds the value of the author edge.
	Author *User `json:"author,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AuthorOrErr returns the Author value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DeploymentsEdges) AuthorOrErr() (*User, error) {
	if e.Author != nil {
		return e.Author, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "author"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Deployments) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case deployments.FieldBranch, deployments.FieldImageTag, deployments.FieldRepoURL, deployments.FieldStatus:
			values[i] = new(sql.NullString)
		case deployments.FieldCreatedAt, deployments.FieldFinishedAt:
			values[i] = new(sql.NullTime)
		case deployments.FieldID:
			values[i] = new(uuid.UUID)
		case deployments.ForeignKeys[0]: // user_deployments
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Deployments fields.
func (_m *Deployments) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case deployments.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case deployments.FieldBranch:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field branch", values[i])
			} else if value.Valid {
				_m.Branch = value.String
			}
		case deployments.FieldImageTag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_tag", values[i])
			} else if value.Valid {
				_m.ImageTag = value.String
			}
		case deployments.FieldRepoURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field repo_url", values[i])
			} else if value.Valid {
				_m.RepoURL = value.String
			}
		case deployments.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case deployments.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case deployments.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case deployments.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_deployments", value)
			} else if value.Valid {
				_m.user_deployments = new(int)
				*_m.user_deployments = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Deployments.
// This includes values selected through modifiers, order, etc.
func (_m *Deployments) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAuthor queries the "author" edge of the Deployments entity.
func (_m *Deployments) QueryAuthor() *UserQuery {
	return NewDeploymentsClient(_m.config).QueryAuthor(_m)
}

// Update returns a builder for updating this Deployments.
// Note that you need to call Deployments.Unwrap() before calling this method if this Deployments
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Deployments) Update() *DeploymentsUpdateOne {
	return NewDeploymentsClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Deployments entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Deployments) Unwrap() *Deployments {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Deployments is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Deployments) String() string {
	var builder strings.Builder
	builder.WriteString("Deployments(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("branch=")
	builder.WriteString(_m.Branch)
	builder.WriteString(", ")
	builder.WriteString("image_tag=")
	builder.WriteString(_m.ImageTag)
	builder.WriteString(", ")
	builder.WriteString("repo_url=")
	builder.WriteString(_m.RepoURL)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// DeploymentsSlice is a parsable slice of Deployments.
type DeploymentsSlice []*Deployments
