// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mini-paas/ent/deployments"
	"mini-paas/ent/predicate"
	"mini-paas/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DeploymentsUpdate is the builder for updating Deployments entities.
type DeploymentsUpdate struct {
	config
	hooks    []Hook
	mutation *DeploymentsMutation
}

// Where appends a list predicates to the DeploymentsUpdate builder.
func (_u *DeploymentsUpdate) Where(ps ...predicate.Deployments) *DeploymentsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBranch sets the "branch" field.
func (_u *DeploymentsUpdate) SetBranch(v string) *DeploymentsUpdate {
	_u.mutation.SetBranch(v)
	return _u
}

// SetNillableBranch sets the "branch" field if the given value is not nil.
func (_u *DeploymentsUpdate) SetNillableBranch(v *string) *DeploymentsUpdate {
	if v != nil {
		_u.SetBranch(*v)
	}
	return _u
}

// SetImageTag sets the "image_tag" field.
func (_u *DeploymentsUpdate) SetImageTag(v string) *DeploymentsUpdate {
	_u.mutation.SetImageTag(v)
	return _u
}

// SetNillableImageTag sets the "image_tag" field if the given value is not nil.
func (_u *DeploymentsUpdate) SetNillableImageTag(v *string) *DeploymentsUpdate {
	if v != nil {
		_u.SetImageTag(*v)
	}
	return _u
}

// SetRepoURL sets the "repo_url" field.
func (_u *DeploymentsUpdate) SetRepoURL(v string) *DeploymentsUpdate {
	_u.mutation.SetRepoURL(v)
	return _u
}

// SetNillableRepoURL sets the "repo_url" field if the given value is not nil.
func (_u *DeploymentsUpdate) SetNillableRepoURL(v *string) *DeploymentsUpdate {
	if v != nil {
		_u.SetRepoURL(*v)
	}
	return _u
}

// SetDomain sets the "Domain" field.
func (_u *DeploymentsUpdate) SetDomain(v string) *DeploymentsUpdate {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "Domain" field if the given value is not nil.
func (_u *DeploymentsUpdate) SetNillableDomain(v *string) *DeploymentsUpdate {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// ClearDomain clears the value of the "Domain" field.
func (_u *DeploymentsUpdate) ClearDomain() *DeploymentsUpdate {
	_u.mutation.ClearDomain()
	return _u
}

// SetStatus sets the "status" field.
func (_u *DeploymentsUpdate) SetStatus(v string) *DeploymentsUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DeploymentsUpdate) SetNillableStatus(v *string) *DeploymentsUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DeploymentsUpdate) SetCreatedAt(v time.Time) *DeploymentsUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DeploymentsUpdate) SetNillableCreatedAt(v *time.Time) *DeploymentsUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (_u *DeploymentsUpdate) SetAuthorID(id int) *DeploymentsUpdate {
	_u.mutation.SetAuthorID(id)
	return _u
}

// SetAuthor sets the "author" edge to the User entity.
func (_u *DeploymentsUpdate) SetAuthor(v *User) *DeploymentsUpdate {
	return _u.SetAuthorID(v.ID)
}

// Mutation returns the DeploymentsMutation object of the builder.
func (_u *DeploymentsUpdate) Mutation() *DeploymentsMutation {
	return _u.mutation
}

// ClearAuthor clears the "author" edge to the User entity.
func (_u *DeploymentsUpdate) ClearAuthor() *DeploymentsUpdate {
	_u.mutation.ClearAuthor()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeploymentsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeploymentsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeploymentsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeploymentsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeploymentsUpdate) check() error {
	if v, ok := _u.mutation.ImageTag(); ok {
		if err := deployments.ImageTagValidator(v); err != nil {
			return &ValidationError{Name: "image_tag", err: fmt.Errorf(`ent: validator failed for field "Deployments.image_tag": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RepoURL(); ok {
		if err := deployments.RepoURLValidator(v); err != nil {
			return &ValidationError{Name: "repo_url", err: fmt.Errorf(`ent: validator failed for field "Deployments.repo_url": %w`, err)}
		}
	}
	if _u.mutation.AuthorCleared() && len(_u.mutation.AuthorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Deployments.author"`)
	}
	return nil
}

func (_u *DeploymentsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deployments.Table, deployments.Columns, sqlgraph.NewFieldSpec(deployments.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Branch(); ok {
		_spec.SetField(deployments.FieldBranch, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImageTag(); ok {
		_spec.SetField(deployments.FieldImageTag, field.TypeString, value)
	}
	if value, ok := _u.mutation.RepoURL(); ok {
		_spec.SetField(deployments.FieldRepoURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(deployments.FieldDomain, field.TypeString, value)
	}
	if _u.mutation.DomainCleared() {
		_spec.ClearField(deployments.FieldDomain, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(deployments.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(deployments.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deployments.AuthorTable,
			Columns: []string{deployments.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deployments.AuthorTable,
			Columns: []string{deployments.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deployments.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeploymentsUpdateOne is the builder for updating a single Deployments entity.
type DeploymentsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeploymentsMutation
}

// SetBranch sets the "branch" field.
func (_u *DeploymentsUpdateOne) SetBranch(v string) *DeploymentsUpdateOne {
	_u.mutation.SetBranch(v)
	return _u
}

// SetNillableBranch sets the "branch" field if the given value is not nil.
func (_u *DeploymentsUpdateOne) SetNillableBranch(v *string) *DeploymentsUpdateOne {
	if v != nil {
		_u.SetBranch(*v)
	}
	return _u
}

// SetImageTag sets the "image_tag" field.
func (_u *DeploymentsUpdateOne) SetImageTag(v string) *DeploymentsUpdateOne {
	_u.mutation.SetImageTag(v)
	return _u
}

// SetNillableImageTag sets the "image_tag" field if the given value is not nil.
func (_u *DeploymentsUpdateOne) SetNillableImageTag(v *string) *DeploymentsUpdateOne {
	if v != nil {
		_u.SetImageTag(*v)
	}
	return _u
}

// SetRepoURL sets the "repo_url" field.
func (_u *DeploymentsUpdateOne) SetRepoURL(v string) *DeploymentsUpdateOne {
	_u.mutation.SetRepoURL(v)
	return _u
}

// SetNillableRepoURL sets the "repo_url" field if the given value is not nil.
func (_u *DeploymentsUpdateOne) SetNillableRepoURL(v *string) *DeploymentsUpdateOne {
	if v != nil {
		_u.SetRepoURL(*v)
	}
	return _u
}

// SetDomain sets the "Domain" field.
func (_u *DeploymentsUpdateOne) SetDomain(v string) *DeploymentsUpdateOne {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "Domain" field if the given value is not nil.
func (_u *DeploymentsUpdateOne) SetNillableDomain(v *string) *DeploymentsUpdateOne {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// ClearDomain clears the value of the "Domain" field.
func (_u *DeploymentsUpdateOne) ClearDomain() *DeploymentsUpdateOne {
	_u.mutation.ClearDomain()
	return _u
}

// SetStatus sets the "status" field.
func (_u *DeploymentsUpdateOne) SetStatus(v string) *DeploymentsUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DeploymentsUpdateOne) SetNillableStatus(v *string) *DeploymentsUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DeploymentsUpdateOne) SetCreatedAt(v time.Time) *DeploymentsUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DeploymentsUpdateOne) SetNillableCreatedAt(v *time.Time) *DeploymentsUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (_u *DeploymentsUpdateOne) SetAuthorID(id int) *DeploymentsUpdateOne {
	_u.mutation.SetAuthorID(id)
	return _u
}

// SetAuthor sets the "author" edge to the User entity.
func (_u *DeploymentsUpdateOne) SetAuthor(v *User) *DeploymentsUpdateOne {
	return _u.SetAuthorID(v.ID)
}

// Mutation returns the DeploymentsMutation object of the builder.
func (_u *DeploymentsUpdateOne) Mutation() *DeploymentsMutation {
	return _u.mutation
}

// ClearAuthor clears the "author" edge to the User entity.
func (_u *DeploymentsUpdateOne) ClearAuthor() *DeploymentsUpdateOne {
	_u.mutation.ClearAuthor()
	return _u
}

// Where appends a list predicates to the DeploymentsUpdate builder.
func (_u *DeploymentsUpdateOne) Where(ps ...predicate.Deployments) *DeploymentsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeploymentsUpdateOne) Select(field string, fields ...string) *DeploymentsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Deployments entity.
func (_u *DeploymentsUpdateOne) Save(ctx context.Context) (*Deployments, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeploymentsUpdateOne) SaveX(ctx context.Context) *Deployments {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeploymentsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeploymentsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeploymentsUpdateOne) check() error {
	if v, ok := _u.mutation.ImageTag(); ok {
		if err := deployments.ImageTagValidator(v); err != nil {
			return &ValidationError{Name: "image_tag", err: fmt.Errorf(`ent: validator failed for field "Deployments.image_tag": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RepoURL(); ok {
		if err := deployments.RepoURLValidator(v); err != nil {
			return &ValidationError{Name: "repo_url", err: fmt.Errorf(`ent: validator failed for field "Deployments.repo_url": %w`, err)}
		}
	}
	if _u.mutation.AuthorCleared() && len(_u.mutation.AuthorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Deployments.author"`)
	}
	return nil
}

func (_u *DeploymentsUpdateOne) sqlSave(ctx context.Context) (_node *Deployments, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deployments.Table, deployments.Columns, sqlgraph.NewFieldSpec(deployments.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Deployments.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deployments.FieldID)
		for _, f := range fields {
			if !deployments.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != deployments.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Branch(); ok {
		_spec.SetField(deployments.FieldBranch, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImageTag(); ok {
		_spec.SetField(deployments.FieldImageTag, field.TypeString, value)
	}
	if value, ok := _u.mutation.RepoURL(); ok {
		_spec.SetField(deployments.FieldRepoURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(deployments.FieldDomain, field.TypeString, value)
	}
	if _u.mutation.DomainCleared() {
		_spec.ClearField(deployments.FieldDomain, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(deployments.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(deployments.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deployments.AuthorTable,
			Columns: []string{deployments.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deployments.AuthorTable,
			Columns: []string{deployments.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Deployments{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deployments.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
