// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"mini-paas/ent/deployments"
	"mini-paas/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DeploymentsDelete is the builder for deleting a Deployments entity.
type DeploymentsDelete struct {
	config
	hooks    []Hook
	mutation *DeploymentsMutation
}

// Where appends a list predicates to the DeploymentsDelete builder.
func (_d *DeploymentsDelete) Where(ps ...predicate.Deployments) *DeploymentsDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DeploymentsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DeploymentsDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DeploymentsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(deployments.Table, sqlgraph.NewFieldSpec(deployments.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DeploymentsDeleteOne is the builder for deleting a single Deployments entity.
type DeploymentsDeleteOne struct {
	_d *DeploymentsDelete
}

// Where appends a list predicates to the DeploymentsDelete builder.
func (_d *DeploymentsDeleteOne) Where(ps ...predicate.Deployments) *DeploymentsDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DeploymentsDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{deployments.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DeploymentsDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
