// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mini-paas/ent/deployments"
	"mini-paas/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// DeploymentsCreate is the builder for creating a Deployments entity.
type DeploymentsCreate struct {
	config
	mutation *DeploymentsMutation
	hooks    []Hook
}

// SetBranch sets the "branch" field.
func (_c *DeploymentsCreate) SetBranch(v string) *DeploymentsCreate {
	_c.mutation.SetBranch(v)
	return _c
}

// SetNillableBranch sets the "branch" field if the given value is not nil.
func (_c *DeploymentsCreate) SetNillableBranch(v *string) *DeploymentsCreate {
	if v != nil {
		_c.SetBranch(*v)
	}
	return _c
}

// SetImageTag sets the "image_tag" field.
func (_c *DeploymentsCreate) SetImageTag(v string) *DeploymentsCreate {
	_c.mutation.SetImageTag(v)
	return _c
}

// SetRepoURL sets the "repo_url" field.
func (_c *DeploymentsCreate) SetRepoURL(v string) *DeploymentsCreate {
	_c.mutation.SetRepoURL(v)
	return _c
}

// SetDomain sets the "Domain" field.
func (_c *DeploymentsCreate) SetDomain(v string) *DeploymentsCreate {
	_c.mutation.SetDomain(v)
	return _c
}

// SetNillableDomain sets the "Domain" field if the given value is not nil.
func (_c *DeploymentsCreate) SetNillableDomain(v *string) *DeploymentsCreate {
	if v != nil {
		_c.SetDomain(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *DeploymentsCreate) SetStatus(v string) *DeploymentsCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DeploymentsCreate) SetNillableStatus(v *string) *DeploymentsCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DeploymentsCreate) SetCreatedAt(v time.Time) *DeploymentsCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DeploymentsCreate) SetNillableCreatedAt(v *time.Time) *DeploymentsCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DeploymentsCreate) SetID(v uuid.UUID) *DeploymentsCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DeploymentsCreate) SetNillableID(v *uuid.UUID) *DeploymentsCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (_c *DeploymentsCreate) SetAuthorID(id int) *DeploymentsCreate {
	_c.mutation.SetAuthorID(id)
	return _c
}

// SetAuthor sets the "author" edge to the User entity.
func (_c *DeploymentsCreate) SetAuthor(v *User) *DeploymentsCreate {
	return _c.SetAuthorID(v.ID)
}

// Mutation returns the DeploymentsMutation object of the builder.
func (_c *DeploymentsCreate) Mutation() *DeploymentsMutation {
	return _c.mutation
}

// Save creates the Deployments in the database.
func (_c *DeploymentsCreate) Save(ctx context.Context) (*Deployments, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DeploymentsCreate) SaveX(ctx context.Context) *Deployments {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeploymentsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeploymentsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DeploymentsCreate) defaults() {
	if _, ok := _c.mutation.Branch(); !ok {
		v := deployments.DefaultBranch
		_c.mutation.SetBranch(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := deployments.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := deployments.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := deployments.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DeploymentsCreate) check() error {
	if _, ok := _c.mutation.Branch(); !ok {
		return &ValidationError{Name: "branch", err: errors.New(`ent: missing required field "Deployments.branch"`)}
	}
	if _, ok := _c.mutation.ImageTag(); !ok {
		return &ValidationError{Name: "image_tag", err: errors.New(`ent: missing required field "Deployments.image_tag"`)}
	}
	if v, ok := _c.mutation.ImageTag(); ok {
		if err := deployments.ImageTagValidator(v); err != nil {
			return &ValidationError{Name: "image_tag", err: fmt.Errorf(`ent: validator failed for field "Deployments.image_tag": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RepoURL(); !ok {
		return &ValidationError{Name: "repo_url", err: errors.New(`ent: missing required field "Deployments.repo_url"`)}
	}
	if v, ok := _c.mutation.RepoURL(); ok {
		if err := deployments.RepoURLValidator(v); err != nil {
			return &ValidationError{Name: "repo_url", err: fmt.Errorf(`ent: validator failed for field "Deployments.repo_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Deployments.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Deployments.created_at"`)}
	}
	if len(_c.mutation.AuthorIDs()) == 0 {
		return &ValidationError{Name: "author", err: errors.New(`ent: missing required edge "Deployments.author"`)}
	}
	return nil
}

func (_c *DeploymentsCreate) sqlSave(ctx context.Context) (*Deployments, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DeploymentsCreate) createSpec() (*Deployments, *sqlgraph.CreateSpec) {
	var (
		_node = &Deployments{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(deployments.Table, sqlgraph.NewFieldSpec(deployments.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Branch(); ok {
		_spec.SetField(deployments.FieldBranch, field.TypeString, value)
		_node.Branch = value
	}
	if value, ok := _c.mutation.ImageTag(); ok {
		_spec.SetField(deployments.FieldImageTag, field.TypeString, value)
		_node.ImageTag = value
	}
	if value, ok := _c.mutation.RepoURL(); ok {
		_spec.SetField(deployments.FieldRepoURL, field.TypeString, value)
		_node.RepoURL = value
	}
	if value, ok := _c.mutation.Domain(); ok {
		_spec.SetField(deployments.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(deployments.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(deployments.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deployments.AuthorTable,
			Columns: []string{deployments.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_deployments = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DeploymentsCreateBulk is the builder for creating many Deployments entities in bulk.
type DeploymentsCreateBulk struct {
	config
	err      error
	builders []*DeploymentsCreate
}

// Save creates the Deployments entities in the database.
func (_c *DeploymentsCreateBulk) Save(ctx context.Context) ([]*Deployments, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Deployments, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeploymentsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DeploymentsCreateBulk) SaveX(ctx context.Context) []*Deployments {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeploymentsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeploymentsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
