name: CI Pipeline

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout-code
              uses: actions/checkout@v4
            
            - name: Setup Go
              uses: actions/setup-go@v5

            - name: Download Dependencies
              run: go mod download

            - name: Run Tests
              run: go test -v ./cmd/api
            
            - name: Build Application
              run: go build -v ./...