// Code generated by ent, DO NOT EDIT.

package deployments

import (
	"mini-paas/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Deployments {
	return predicate.Deployments(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Deployments {
	return predicate.Deployments(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Deployments {
	return predicate.Deployments(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Deployments {
	return predicate.Deployments(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Deployments {
	return predicate.Deployments(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Deployments {
	return predicate.Deployments(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Deployments {
	return predicate.Deployments(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Deployments {
	return predicate.Deployments(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Deployments {
	return predicate.Deployments(sql.FieldLTE(FieldID, id))
}

// Branch applies equality check predicate on the "branch" field. It's identical to BranchEQ.
func Branch(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldEQ(FieldBranch, v))
}

// ImageTag applies equality check predicate on the "image_tag" field. It's identical to ImageTagEQ.
func ImageTag(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldEQ(FieldImageTag, v))
}

// RepoURL applies equality check predicate on the "repo_url" field. It's identical to RepoURLEQ.
func RepoURL(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldEQ(FieldRepoURL, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Deployments {
	return predicate.Deployments(sql.FieldEQ(FieldCreatedAt, v))
}

// BranchEQ applies the EQ predicate on the "branch" field.
func BranchEQ(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldEQ(FieldBranch, v))
}

// BranchNEQ applies the NEQ predicate on the "branch" field.
func BranchNEQ(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldNEQ(FieldBranch, v))
}

// BranchIn applies the In predicate on the "branch" field.
func BranchIn(vs ...string) predicate.Deployments {
	return predicate.Deployments(sql.FieldIn(FieldBranch, vs...))
}

// BranchNotIn applies the NotIn predicate on the "branch" field.
func BranchNotIn(vs ...string) predicate.Deployments {
	return predicate.Deployments(sql.FieldNotIn(FieldBranch, vs...))
}

// BranchGT applies the GT predicate on the "branch" field.
func BranchGT(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldGT(FieldBranch, v))
}

// BranchGTE applies the GTE predicate on the "branch" field.
func BranchGTE(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldGTE(FieldBranch, v))
}

// BranchLT applies the LT predicate on the "branch" field.
func BranchLT(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldLT(FieldBranch, v))
}

// BranchLTE applies the LTE predicate on the "branch" field.
func BranchLTE(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldLTE(FieldBranch, v))
}

// BranchContains applies the Contains predicate on the "branch" field.
func BranchContains(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldContains(FieldBranch, v))
}

// BranchHasPrefix applies the HasPrefix predicate on the "branch" field.
func BranchHasPrefix(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldHasPrefix(FieldBranch, v))
}

// BranchHasSuffix applies the HasSuffix predicate on the "branch" field.
func BranchHasSuffix(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldHasSuffix(FieldBranch, v))
}

// BranchEqualFold applies the EqualFold predicate on the "branch" field.
func BranchEqualFold(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldEqualFold(FieldBranch, v))
}

// BranchContainsFold applies the ContainsFold predicate on the "branch" field.
func BranchContainsFold(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldContainsFold(FieldBranch, v))
}

// ImageTagEQ applies the EQ predicate on the "image_tag" field.
func ImageTagEQ(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldEQ(FieldImageTag, v))
}

// ImageTagNEQ applies the NEQ predicate on the "image_tag" field.
func ImageTagNEQ(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldNEQ(FieldImageTag, v))
}

// ImageTagIn applies the In predicate on the "image_tag" field.
func ImageTagIn(vs ...string) predicate.Deployments {
	return predicate.Deployments(sql.FieldIn(FieldImageTag, vs...))
}

// ImageTagNotIn applies the NotIn predicate on the "image_tag" field.
func ImageTagNotIn(vs ...string) predicate.Deployments {
	return predicate.Deployments(sql.FieldNotIn(FieldImageTag, vs...))
}

// ImageTagGT applies the GT predicate on the "image_tag" field.
func ImageTagGT(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldGT(FieldImageTag, v))
}

// ImageTagGTE applies the GTE predicate on the "image_tag" field.
func ImageTagGTE(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldGTE(FieldImageTag, v))
}

// ImageTagLT applies the LT predicate on the "image_tag" field.
func ImageTagLT(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldLT(FieldImageTag, v))
}

// ImageTagLTE applies the LTE predicate on the "image_tag" field.
func ImageTagLTE(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldLTE(FieldImageTag, v))
}

// ImageTagContains applies the Contains predicate on the "image_tag" field.
func ImageTagContains(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldContains(FieldImageTag, v))
}

// ImageTagHasPrefix applies the HasPrefix predicate on the "image_tag" field.
func ImageTagHasPrefix(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldHasPrefix(FieldImageTag, v))
}

// ImageTagHasSuffix applies the HasSuffix predicate on the "image_tag" field.
func ImageTagHasSuffix(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldHasSuffix(FieldImageTag, v))
}

// ImageTagEqualFold applies the EqualFold predicate on the "image_tag" field.
func ImageTagEqualFold(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldEqualFold(FieldImageTag, v))
}

// ImageTagContainsFold applies the ContainsFold predicate on the "image_tag" field.
func ImageTagContainsFold(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldContainsFold(FieldImageTag, v))
}

// RepoURLEQ applies the EQ predicate on the "repo_url" field.
func RepoURLEQ(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldEQ(FieldRepoURL, v))
}

// RepoURLNEQ applies the NEQ predicate on the "repo_url" field.
func RepoURLNEQ(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldNEQ(FieldRepoURL, v))
}

// RepoURLIn applies the In predicate on the "repo_url" field.
func RepoURLIn(vs ...string) predicate.Deployments {
	return predicate.Deployments(sql.FieldIn(FieldRepoURL, vs...))
}

// RepoURLNotIn applies the NotIn predicate on the "repo_url" field.
func RepoURLNotIn(vs ...string) predicate.Deployments {
	return predicate.Deployments(sql.FieldNotIn(FieldRepoURL, vs...))
}

// RepoURLGT applies the GT predicate on the "repo_url" field.
func RepoURLGT(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldGT(FieldRepoURL, v))
}

// RepoURLGTE applies the GTE predicate on the "repo_url" field.
func RepoURLGTE(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldGTE(FieldRepoURL, v))
}

// RepoURLLT applies the LT predicate on the "repo_url" field.
func RepoURLLT(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldLT(FieldRepoURL, v))
}

// RepoURLLTE applies the LTE predicate on the "repo_url" field.
func RepoURLLTE(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldLTE(FieldRepoURL, v))
}

// RepoURLContains applies the Contains predicate on the "repo_url" field.
func RepoURLContains(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldContains(FieldRepoURL, v))
}

// RepoURLHasPrefix applies the HasPrefix predicate on the "repo_url" field.
func RepoURLHasPrefix(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldHasPrefix(FieldRepoURL, v))
}

// RepoURLHasSuffix applies the HasSuffix predicate on the "repo_url" field.
func RepoURLHasSuffix(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldHasSuffix(FieldRepoURL, v))
}

// RepoURLEqualFold applies the EqualFold predicate on the "repo_url" field.
func RepoURLEqualFold(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldEqualFold(FieldRepoURL, v))
}

// RepoURLContainsFold applies the ContainsFold predicate on the "repo_url" field.
func RepoURLContainsFold(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldContainsFold(FieldRepoURL, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Deployments {
	return predicate.Deployments(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Deployments {
	return predicate.Deployments(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Deployments {
	return predicate.Deployments(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Deployments {
	return predicate.Deployments(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Deployments {
	return predicate.Deployments(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Deployments {
	return predicate.Deployments(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Deployments {
	return predicate.Deployments(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Deployments {
	return predicate.Deployments(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Deployments {
	return predicate.Deployments(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Deployments {
	return predicate.Deployments(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Deployments {
	return predicate.Deployments(sql.FieldLTE(FieldCreatedAt, v))
}

// HasAuthor applies the HasEdge predicate on the "author" edge.
func HasAuthor() predicate.Deployments {
	return predicate.Deployments(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AuthorTable, AuthorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAuthorWith applies the HasEdge predicate on the "author" edge with a given conditions (other predicates).
func HasAuthorWith(preds ...predicate.User) predicate.Deployments {
	return predicate.Deployments(func(s *sql.Selector) {
		step := newAuthorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Deployments) predicate.Deployments {
	return predicate.Deployments(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Deployments) predicate.Deployments {
	return predicate.Deployments(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Deployments) predicate.Deployments {
	return predicate.Deployments(sql.NotPredicates(p))
}
